"use strict"
const bcrypt = require("bcrypt")

module.exports = {
  async up(queryInterface) {
    const hash = (pw) => bcrypt.hashSync(pw, 10)

    await queryInterface.bulkInsert("users", [

      // ── Admin ─────────────────────────────────────────────
      {
        id:           1,
        name:         "Admin System",
        email:        "admin@school.edu",
        password:     hash("admin123"),
        role:         "admin",
        profile_image: "https://api.dicebear.com/7.x/notionists/svg?seed=Admin",
        phone:        "012 000 001",
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },

      // ── Teachers ──────────────────────────────────────────
      {
        id:           2,
        name:         "Sokha Lim",
        email:        "sokha@school.edu",
        password:     hash("teacher123"),
        role:         "teacher",
        profile_image: "https://api.dicebear.com/7.x/notionists/svg?seed=Sokha",
        phone:        "012 111 001",
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           3,
        name:         "Nary Chan",
        email:        "nary@school.edu",
        password:     hash("teacher123"),
        role:         "teacher",
        profile_image: "https://api.dicebear.com/7.x/notionists/svg?seed=Nary",
        phone:        "012 111 002",
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           4,
        name:         "Visal Pov",
        email:        "visal@school.edu",
        password:     hash("teacher123"),
        role:         "teacher",
        profile_image: "https://api.dicebear.com/7.x/notionists/svg?seed=Visal",
        phone:        "012 111 003",
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           5,
        name:         "Bopha Keo",
        email:        "bopha.t@school.edu",
        password:     hash("teacher123"),
        role:         "teacher",
        profile_image: "https://api.dicebear.com/7.x/notionists/svg?seed=BophaT",
        phone:        "012 111 004",
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },

      // ── Parents ───────────────────────────────────────────
      {
        id:           6,
        name:         "Chan Sopheak",
        email:        "sopheak@gmail.com",
        password:     hash("parent123"),
        role:         "parent",
        profile_image: "https://api.dicebear.com/7.x/lorelei/svg?seed=ChanSopheak",
        phone:        "012 987 001",
        relationship: "Father",
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           7,
        name:         "Keo Bunna",
        email:        "bunna@gmail.com",
        password:     hash("parent123"),
        role:         "parent",
        profile_image: "https://api.dicebear.com/7.x/lorelei/svg?seed=KeoBunna",
        phone:        "012 987 002",
        relationship: "Mother",
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           8,
        name:         "Ly Ratha",
        email:        "ratha@gmail.com",
        password:     hash("parent123"),
        role:         "parent",
        profile_image: "https://api.dicebear.com/7.x/lorelei/svg?seed=LyRatha",
        phone:        "012 987 003",
        relationship: "Father",
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           9,
        name:         "Pov Channary",
        email:        "channary@gmail.com",
        password:     hash("parent123"),
        role:         "parent",
        profile_image: "https://api.dicebear.com/7.x/lorelei/svg?seed=PovChannary",
        phone:        "012 987 004",
        relationship: "Mother",
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           10,
        name:         "Meas Sokha",
        email:        "meas@gmail.com",
        password:     hash("parent123"),
        role:         "parent",
        profile_image: "https://api.dicebear.com/7.x/lorelei/svg?seed=MeasSokha",
        phone:        "012 987 005",
        relationship: "Guardian",
        created_at:   new Date(),
        updated_at:   new Date(),
      },

      // ── Students ──────────────────────────────────────────
      {
        id:           11,
        name:         "Sophea Chan",
        email:        "sophea@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sophea&backgroundColor=b6e3f4",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           12,
        name:         "Piseth Keo",
        email:        "piseth@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Piseth&backgroundColor=ffd5dc",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           13,
        name:         "Sreymom Ly",
        email:        "sreymom@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Sreymom&backgroundColor=d1f4d1",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           14,
        name:         "Dara Pov",
        email:        "dara@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Dara&backgroundColor=ffe4b5",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           15,
        name:         "Kimheng Meas",
        email:        "kimheng@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=Kimheng&backgroundColor=e8d5f4",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },
      {
        id:           16,
        name:         "Bopha Meas",
        email:        "bophas@school.edu",
        password:     hash("student123"),
        role:         "student",
        profile_image: "https://api.dicebear.com/7.x/avataaars/svg?seed=BophaS&backgroundColor=f4d5b6",
        phone:        null,
        relationship: null,
        created_at:   new Date(),
        updated_at:   new Date(),
      },

    ], {})
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("users", null, {})
  },
}
